name: CI

on: [push]

jobs:

  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 8.x
    - name: Cache node modules
      id: cache
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-nodemodules-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}-3
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        # HACK: Install all deps except puppeteer (see #2539)
        yarn remove puppeteer
      env:
        CI: true
    - name: Build
      run: yarn prepare
    - name: Lint
      run: yarn lint
    - name: ls
      run: ls -lR out
    - name: Upload out/
      uses: actions/upload-artifact@v1
      with:
        name: out
        path: out
    - name: Upload out-test/
      uses: actions/upload-artifact@v1
      with:
        name: out-test
        path: out-test

  linux-test-unit:
    needs: linux-build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 8.x
    - name: Cache node modules
      id: cache
      uses: actions/cache@v1
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Download out/
      uses: actions/download-artifact@v1
      with:
        name: out
    - name: Download out-test/
      uses: actions/download-artifact@v1
      with:
        name: out-test
    - name: ls
      run: ls -lR out
    - name: Run unit tests
      run: yarn test-unit --forbid-only

